# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wedding.fields


class Migration(migrations.Migration):

    replaces = [('wedding', '0016_auto_20180505_2127'), ('wedding', '0017_auto_20180505_2129')]

    dependencies = [
        ('wedding', '0015_event_directions_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='home_airport',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='pnr',
            field=wedding.fields.PnrField(max_length=6, unique=True, verbose_name='Confirmation Code'),
        ),
        migrations.AddField(
            model_name='mailsent',
            name='last_opened',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='address_city',
            field=models.CharField(blank=True, max_length=80, verbose_name='City/Suburb'),
        ),
        migrations.AlterField(
            model_name='group',
            name='address_state_province',
            field=models.CharField(blank=True, max_length=80, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='group',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='mailsent',
            name='open_key',
            field=wedding.fields.PnrField(default='AAAAAA', max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='mailsent',
            options={'verbose_name_plural': 'Mails sent'},
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='wedding.Group')),
            ],
        ),
        migrations.CreateModel(
            name='NeedToSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.IntegerField(choices=[(1, 'Invitation'), (2, 'Thank you card')])),
                ('why', models.TextField()),
                ('added', models.DateField(auto_now_add=True)),
                ('sent', models.DateField(blank=True, default=None, null=True)),
                ('sent_note', models.TextField(blank=True)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.Group')),
            ],
        ),
        migrations.RenameField(
            model_name='mailout',
            old_name='plain_text',
            new_name='plain_body',
        ),
        migrations.AddField(
            model_name='mailout',
            name='html_body',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailouts_from_email', models.EmailField(max_length=254)),
                ('mailouts_bcc', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('physical_address', models.TextField(blank=True)),
                ('mailouts_from_name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='MailoutImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('mailout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.Mailout')),
                ('slug', models.SlugField(default='slug')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mailoutimage',
            unique_together=set([('slug', 'mailout')]),
        ),
        migrations.AlterField(
            model_name='mailoutimage',
            name='mailout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wedding.Mailout'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='name_flagged',
        ),
        migrations.AlterField(
            model_name='group',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='groups', to='wedding.Event'),
        ),
        migrations.AlterField(
            model_name='mailsent',
            name='datestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mailoutimage',
            name='slug',
            field=models.SlugField(),
        ),
    ]
