# Generated by Django 2.0.5 on 2018-05-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0017_auto_20180506_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needtosend',
            name='what',
            field=models.IntegerField(choices=[(1, 'Invitation'), (2, 'Thank you card'), (3, 'Save the date')]),
        ),
    ]
