# Generated by Django 2.0.5 on 2018-05-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0020_auto_20180522_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['display_name']},
        ),
    ]
