# Generated by Django 2.0.5 on 2018-11-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0021_auto_20180528_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsSection',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='HTML is permitted')),
                ('order', models.IntegerField(default=0)),
                ('add_paragraph_tags', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='details_sections',
            field=models.ManyToManyField(
                blank=True, related_name='groups', to='wedding.DetailsSection'),
        ),
    ]
