# Generated by Django 2.0.5 on 2018-11-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0022_detailssection'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='accepting_rsvps',
            field=models.BooleanField(
                default=False, verbose_name='Accepting RSVPs'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rsvp_status',
            field=models.IntegerField(choices=[(
                1, 'No response'), (2, 'Attending'), (3, 'Not attending')], default=1, verbose_name='RSVP'),
        ),
    ]
